### ISSUE TITLE
Link zu eigenem Profil nicht abrufbar

### ISSUE THREAD

**Issue by oliof** [pflenker/spielerunde.org#5]
Ich würde gerne den Link zu meinem eigenen Profil abrufen können. Damit könnte ich zwei Dinge tun:

1. Überprüfen, wie andere mein Profil sehen.
2. Mein Profil auf anderen Seiten (Foren, Social Networks) verlinken.

**Comment by pflenker** [comment]
Hi, dieses Problem wurde mit der aktuellen Version gelöst. Du kannst Dein Profil nun so sehen, wie es andere sehen werden, indem Du als eingeloggter Benutzer https://www.spielerunde.org/profil/ besuchst.
