### ISSUE TITLE
Suche nach Online-Runden UND lokalen Runden nicht möglich.

### ISSUE THREAD

**Issue by oliof** [pflenker/spielerunde.org#6]
Wenn ich den Haken bei 'Online-Suche' setze, kann ich kein Suchgebiet mehr angeben. Das ist sehr schade.

**Comment by pflenker** [comment]
Hi, das funktioniert so, wie es soll, denn bei Online-Spielern soll der Ort ja prinzipiell egal sein, und bei Spielern in der Umgebung ist es egal, ob sie auch online spielen oder nicht.

**Comment by oliof** [comment]
Naja, ich suche aber potentiell _beides zur gleichen Zeit_. Brauche ich
dafür dann zwei Profile?

2015-06-29 7:38 GMT+02:00 Philipp <notifications@github.com>:

**Comment by pflenker** [comment]
Die Suche hat mit dem Profil nichts zu tun: Du kannst in Deinem Profil eintragen, dass Du Online-Spieler bist, und in welchem Ort Du nach Spielern suchst. Du wirst dann sowohl von Spielern, die nach Online-Spielern suchen, als auch von Spielern, die im gleichen Ort suchen wie Du, gefunden.

Lediglich bei der Suche bedeutet das, dass Du Dich entscheiden musst, ob Dir Online-Spieler oder Spieler aus der Umgebung in den Suchergebnissen angezeigt werden.

**Comment by pflenker** [comment]
Ich habe in unserer Hilfe einmal einen entsprechenden Artikel erstellt: https://spielerunde.zendesk.com/hc/de/articles/203629491-Wie-funktioniert-die-Suche-
